name: Xcode - Build and Analyze

# This is a basic workflow to help you get started with Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Make a IPA file
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 #checkout 代码
        
      #- name: Pod install
       # run: pod install
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%m%d%H%m')"
        
      - name: Get current path
        id: path
        run: echo "::set-output name=path::${{ github.workspace }}/${{ steps.date.outputs.date }}/${{ github.run_number }}/me.ipa"

      - uses: yukiarrr/ios-build-action@v1.5.0
        with:
            project-path: ios-build-action-demo.xcodeproj
            workspace-path: ios-build-action-demo.xcworkspace
            p12-base64: ${{ secrets.P12_BASE64}}
            mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64}}
            code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
            team-id: ${{ secrets.TEAM_ID }}
            export-method: 'ad-hoc'
           # output-path: output.ipa
            output-path: ${{ steps.path.outputs.path }}
            
      - name: push to fir
        id: PushToFir
       # run: curl -F file=@${{ github.workspace }}/output.ipa -F '_api_key=9305e44d1f8756988b5edbad024503c1' https://www.pgyer.com/apiv2/app/upload
        run: curl -F file=@${{ steps.path.outputs.path }} -F '_api_key=9305e44d1f8756988b5edbad024503c1' https://www.pgyer.com/apiv2/app/upload
